### ISSUE TITLE
.fuse_hidden00001e9800000001 managed in Git

### ISSUE THREAD

**Issue by hartwork** [lihongxun945/joker#1]
Hi!

It seems you have a Vim 7.2 swap file in this Git repository under 
https://github.com/lihongxun945/joker/blob/master/js/.fuse_hidden00001e9800000001.
I suppose it went in by accident.

Best, Sebastian

**Comment by lihongxun945** [comment]
Thank you!
But this repo is not maintenance yet.It's only for fun.

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
